apiVersion: kuma.io/v1alpha1
kind: OPAPolicy
mesh: default
metadata:
  name: opa-1
spec:
  selectors:
  - match:
      kuma.io/service: backend_kuma-demo_svc_3001
  conf:
    agentConfig:
      inlineString: |
        decision_logs:
          console: true
    policies:
      - inlineString: |
          package envoy.authz

          import input.attributes.request.http as http_request

          default allow = false

          allow {
            http_request.host == "mockbin.org"
            http_request.method == "GET"
            input.parsed_path == ["request"]
          }

          allow {
            http_request.host != "mockbin.org"
          }